-- Canonical editorial seed: initial public posts live in D1.
INSERT OR IGNORE INTO posts(id,title,slug,excerpt,content_html,featured_image,author_user_id,category_id,status,published_at,seo_title,seo_description,canonical_url,og_image,robots,schema_json,focus_keyword,content_type,cluster_slug,primary_keyword,search_intent,seo_priority,reviewed_at,reviewed_by,sources_json,experience_note,featured,reading_time,created_at,updated_at) VALUES ('post-primeiros-passos-web','Primeiros passos para criar seu primeiro site','primeiros-passos-web','Um guia simples para entender HTML, CSS, JavaScript e publicar seu primeiro projeto na web.','<p>Criar um site pode parecer complicado no começo, mas você não precisa aprender tudo de uma vez.</p><h2>1. Comece pelo HTML</h2><p>O HTML define a estrutura da página: títulos, textos, links, imagens e outros elementos.</p><pre><code>&lt;h1&gt;Meu primeiro site&lt;/h1&gt;
&lt;p&gt;Estou começando minha jornada na web.&lt;/p&gt;</code></pre><h2>2. Use CSS para criar o visual</h2><p>O CSS controla cores, espaçamentos, tipografia e responsividade.</p><pre><code>body {
  font-family: sans-serif;
  line-height: 1.6;
}</code></pre><h2>3. Adicione JavaScript quando precisar de interação</h2><p>JavaScript permite criar menus, filtros, formulários e outras experiências interativas.</p><h2>4. Publique seu projeto</h2><p>Depois de construir e testar, você pode colocar o site online usando GitHub e uma plataforma de hospedagem como Cloudflare Pages.</p><h2>Próximo passo</h2><p>Agora que você conhece a base, o próximo objetivo é criar uma página completa e publicar seu primeiro projeto.</p>',NULL,'user-admin-seed','cat-programacao','published','2026-09-01T12:00:00Z',NULL,NULL,NULL,NULL,'index,follow',NULL,NULL,'cluster','fundamentos-web','como criar um site','informacional','alta','2026-09-02','Equipe editorial Dejotacode','[]','Conteúdo produzido com foco em aplicação prática, linguagem acessível e atualização editorial contínua.',1,6,datetime('now'),datetime('now'));
INSERT OR IGNORE INTO tags(id,name,slug,created_at,updated_at) VALUES ('tag-html','html','html',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO post_tags(post_id,tag_id) VALUES ('post-primeiros-passos-web','tag-html');
INSERT OR IGNORE INTO tags(id,name,slug,created_at,updated_at) VALUES ('tag-css','css','css',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO post_tags(post_id,tag_id) VALUES ('post-primeiros-passos-web','tag-css');
INSERT OR IGNORE INTO tags(id,name,slug,created_at,updated_at) VALUES ('tag-javascript','javascript','javascript',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO post_tags(post_id,tag_id) VALUES ('post-primeiros-passos-web','tag-javascript');
INSERT OR IGNORE INTO posts(id,title,slug,excerpt,content_html,featured_image,author_user_id,category_id,status,published_at,seo_title,seo_description,canonical_url,og_image,robots,schema_json,focus_keyword,content_type,cluster_slug,primary_keyword,search_intent,seo_priority,reviewed_at,reviewed_by,sources_json,experience_note,featured,reading_time,created_at,updated_at) VALUES ('post-ia-para-iniciantes','IA para iniciantes: por onde começar','ia-para-iniciantes','Um mapa simples para começar a usar inteligência artificial no estudo, trabalho e criação de conteúdo.','<p>Você não precisa conhecer dezenas de ferramentas para começar a usar IA.</p><h2>Comece por uma tarefa real</h2><p>Escolha uma atividade repetitiva e use IA para acelerar pesquisa, organização, escrita ou análise.</p>',NULL,'user-admin-seed','cat-ia','published','2026-08-26T12:00:00Z',NULL,NULL,NULL,NULL,'index,follow',NULL,NULL,'cluster','ia-na-pratica','IA para iniciantes','informacional','alta','2026-09-02','Equipe editorial Dejotacode','[]','Conteúdo produzido com foco em aplicação prática, linguagem acessível e atualização editorial contínua.',0,4,datetime('now'),datetime('now'));
INSERT OR IGNORE INTO tags(id,name,slug,created_at,updated_at) VALUES ('tag-ia','ia','ia',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO post_tags(post_id,tag_id) VALUES ('post-ia-para-iniciantes','tag-ia');
INSERT OR IGNORE INTO tags(id,name,slug,created_at,updated_at) VALUES ('tag-produtividade','produtividade','produtividade',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO post_tags(post_id,tag_id) VALUES ('post-ia-para-iniciantes','tag-produtividade');
INSERT OR IGNORE INTO posts(id,title,slug,excerpt,content_html,featured_image,author_user_id,category_id,status,published_at,seo_title,seo_description,canonical_url,og_image,robots,schema_json,focus_keyword,content_type,cluster_slug,primary_keyword,search_intent,seo_priority,reviewed_at,reviewed_by,sources_json,experience_note,featured,reading_time,created_at,updated_at) VALUES ('post-publicar-site','Como publicar um site pela primeira vez','publicar-site','Passo a passo para sair do computador local e colocar um projeto web acessível pela internet.','<p>Publicar um site envolve três etapas: preparar o projeto, versionar o código e configurar a hospedagem.</p><h2>1. Teste localmente</h2><p>Confirme que o projeto funciona antes de publicar.</p><h2>2. Envie para um repositório</h2><p>Use Git para manter histórico e enviar o projeto para o GitHub.</p><h2>3. Configure o deploy</h2><p>Conecte o repositório a uma plataforma de hospedagem e faça o primeiro deploy.</p>',NULL,'user-admin-seed','cat-tutoriais-guias','published','2026-08-24T12:00:00Z',NULL,NULL,NULL,NULL,'index,follow',NULL,NULL,'cluster','tutoriais-resolutivos','como publicar um site','informacional','alta','2026-09-02','Equipe editorial Dejotacode','[]','Conteúdo produzido com foco em aplicação prática, linguagem acessível e atualização editorial contínua.',0,7,datetime('now'),datetime('now'));
INSERT OR IGNORE INTO tags(id,name,slug,created_at,updated_at) VALUES ('tag-tutorial','tutorial','tutorial',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO post_tags(post_id,tag_id) VALUES ('post-publicar-site','tag-tutorial');
INSERT OR IGNORE INTO tags(id,name,slug,created_at,updated_at) VALUES ('tag-hospedagem','hospedagem','hospedagem',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO post_tags(post_id,tag_id) VALUES ('post-publicar-site','tag-hospedagem');
INSERT OR IGNORE INTO tags(id,name,slug,created_at,updated_at) VALUES ('tag-github','github','github',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO post_tags(post_id,tag_id) VALUES ('post-publicar-site','tag-github');
INSERT OR IGNORE INTO posts(id,title,slug,excerpt,content_html,featured_image,author_user_id,category_id,status,published_at,seo_title,seo_description,canonical_url,og_image,robots,schema_json,focus_keyword,content_type,cluster_slug,primary_keyword,search_intent,seo_priority,reviewed_at,reviewed_by,sources_json,experience_note,featured,reading_time,created_at,updated_at) VALUES ('post-primeiro-freelance','Como começar no freelancing sem complicar','primeiro-freelance','Um roteiro inicial para escolher uma habilidade, montar uma oferta simples e buscar o primeiro cliente.','<p>Começar como freelancer fica mais fácil quando você transforma uma habilidade em uma oferta clara.</p><h2>Escolha um serviço</h2><p>Comece com algo que você consegue entregar bem: criação de páginas, edição, design, automação ou suporte técnico.</p><h2>Monte uma oferta simples</h2><p>Explique o problema que você resolve, o que entrega e qual é o próximo passo para contratar.</p>',NULL,'user-admin-seed','cat-renda-digital','published','2026-08-28T12:00:00Z',NULL,NULL,NULL,NULL,'index,follow',NULL,NULL,'cluster','primeira-renda-digital','como ser freelancer','informacional','alta','2026-09-02','Equipe editorial Dejotacode','[]','Conteúdo produzido com foco em aplicação prática, linguagem acessível e atualização editorial contínua.',0,5,datetime('now'),datetime('now'));
INSERT OR IGNORE INTO tags(id,name,slug,created_at,updated_at) VALUES ('tag-freelancing','freelancing','freelancing',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO post_tags(post_id,tag_id) VALUES ('post-primeiro-freelance','tag-freelancing');
INSERT OR IGNORE INTO tags(id,name,slug,created_at,updated_at) VALUES ('tag-renda-extra','renda-extra','renda-extra',datetime('now'),datetime('now'));
INSERT OR IGNORE INTO post_tags(post_id,tag_id) VALUES ('post-primeiro-freelance','tag-renda-extra');
